spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gtd8983@gmail.com
    password: //
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: //
            client-secret: //
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        # show_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace

app:
  kakaomap: //
  weather: //

jwt:
  issuer: amung@gmail.com
  secret_key: //

cloud:
  aws:
    credentials:
      accessKey: //
      secretKey: //
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: //