#워크플로 이름
name : CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

        #CD 내용추가
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Beanstalk Deploy
        run:
          command: eb deploy --no-verify-ssl --no-wait
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
            application_name: library
            environment_name: library-env
            version_label: github-action-${{steps.current-time.outputs.formattedTime}}
            region: ap-northeast-2
            deployment_package: ./build/libs/blog-0.0.1-SNAPSHOT.jar

